#include "Traindir3.h"
#include "localize.h"

LocalizeInfo italiano[] = {

	{ wxT("Arrival"), wxT("Arrivo") },
	{ wxT("From"), wxT("Da") },
	{ wxT("To"), wxT("Per") },
	{ wxT("Train"), wxT("Treno") },
	{ wxT("Speed"), wxT("Velocita'") },
	{ wxT("Min.Del."), wxT("Rit.Ingr.") },
	{ wxT("Min.Late"), wxT("Ritardo") },
	{ wxT("Status"), wxT("Stato") },

	{ wxT("Entry"), wxT("Entrata") },
	{ wxT("Exit"), wxT("Uscita") },
	{ wxT("Entry/exit"), wxT("Ingr./Uscita") },
	{ wxT("Times"), wxT("Tempi") },

	{ wxT("Performance Statistics"), wxT("Statistica Prestazioni") },
	{ wxT("Save"), wxT("Salva") },

	{ wxT("Departing trains"), wxT("Treni in partenza") },
	{ wxT("Train Schedule"), wxT("Orario dei treni") },

	{ wxT("Close"), wxT("Chiudi") },
	{ wxT("Stats"), wxT("Statist.") },
	{ wxT("Print..."), wxT("Stampa...") },
	{ wxT("Assign"), wxT("Assegna") },
	{ wxT("Shunt"), wxT("Manovra") },
	{ wxT("Cancel"), wxT("Cancella") },
	{ wxT("Properties"), wxT("Proprieta'") },
	{ wxT("Hide/Show titles"), wxT("Mostra/Nascondi titoli") },

	{ wxT("Name"), wxT("Nome") },
	{ wxT("Sections"), wxT("Sezioni") },

	{ wxT("Track properties"), wxT("Proprieta' del tratto di binario") },
	{ wxT("Track %d,%d"), wxT("Binario %d,%d") },
	{ wxT("Length :"), wxT("Lunghezza ") },
	{ wxT("Speed :"), wxT("Velocita'") },
	{ wxT("Station :"), wxT("Stazione") },
	{ wxT("Linked to west :"), wxT("Collegato a ovest :") },
	{ wxT("Controls :"), wxT("Controlla") },
	{ wxT("Linked to east :"), wxT("Collegato a est :") },

	{ wxT("Switch"), wxT("Scambio") },
	{ wxT("Trigger"), wxT("Pedale") },
	{ wxT("Trigger properties"), wxT("Proprieta' pedale") },
	{ wxT("Trigger at  %d,%d"), wxT("Pedale a  %d,%d") },
	{ wxT("Action :"), wxT("Azione :") },
	{ wxT("'@' in action = name of triggering train"), wxT("'@' nell'azione = nome treno attivante") },
	{ wxT("Linked to track at coord:"), wxT("Collegato al binario :") },
	{ wxT("Probabilities for action :"), wxT("Probabilita' di azionamento :") },

	{ wxT("Signal properties"), wxT("Proprieta' del segnale") },
	{ wxT("Signal at %d,%d"), wxT("Segnale a %d,%d") },
	{ wxT("Signal Name :"), wxT("Nome segnale") },
	{ wxT("Signal is always red"), wxT("Segnale sempre rosso") },
	{ wxT("Signal has square frame"), wxT("Segnale a vela quadra") },
	{ wxT("No penalty for train stopping at this signal"), wxT("Nessuna penalita' per treni fermi a questo segnale") },
	{ wxT("Hidden"), wxT("Invisibile") },
	{ wxT("Script file :"), wxT("File script :") },

	{ wxT("Select Itinerary"), wxT("Scelta Itinerario") },
	{ wxT("Select itinerary"), wxT("Scelta itinerario") },
	{ wxT("Start Signal"), wxT("Segnale di Inizio") },
	{ wxT("End Signal"), wxT("Segnale di Fine") },
	{ wxT("Next Itinerary"), wxT("Prossimo Itinerario") },
	{ wxT("&Select"), wxT("&Scegli") },
        { wxT("For S&hunting"), wxT("Per Man&ovra") },
	{ wxT("&Clear"), wxT("&Annulla") },
	{ wxT("Cl&ose"), wxT("&Chiudi") },

	{ wxT("Territory Information"), wxT("Informazioni sul territorio") },
	{ wxT("Update"), wxT("Aggiorna") },
	{ wxT("Print"), wxT("Stampa") },

	{ wxT("Schedule"), wxT("Orario") },
	{ wxT("Alerts"), wxT("Eventi") },
	{ wxT("Train Info"), wxT("Dettagli Treno") },

	{ wxT("Day Selection"), wxT("Selezione Giorno") },
	{ wxT("Not all trains run every day of the week.\nWhich day do you want to simulate?"), wxT("Non tutti i treni circolano ogni\ngiorno della settimana. Quale giorno vuoi simulare?") },
	{ wxT("Monday"), wxT("Lunedi'") },
	{ wxT("Tuesday"), wxT("Martedi'") },
	{ wxT("Wednesday"), wxT("Mercoledi'") },
	{ wxT("Thursday"), wxT("Giovedi'") },
	{ wxT("Friday"), wxT("Venerdi'") },
	{ wxT("Saturday"), wxT("Sabato") },
	{ wxT("Sunday"), wxT("Domenica") },

	{ wxT("Write default preferences to ini file?"), wxT("Scrivo le preferenze nel file ini?") },
	{ wxT("Preferences"), wxT("Preferenze") },
	{ wxT("Full status info"), wxT("Informazioni di stato complete") },
	{ wxT("Status line at top of window"), wxT("Linea di stato in alto") },
	{ wxT("Alert sound on"), wxT("Suono di avviso") },
	{ wxT("Beep on train entering scenario"), wxT("Suono su ingresso treno") },
	{ wxT("View speed limits"), wxT("Mostra limiti velocita'") },
	{ wxT("Automatically link signals"), wxT("Collega segnali automaticamente") },
	{ wxT("Show grid"), wxT("Mostra griglia") },
	{ wxT("View long blocks"), wxT("Mostra blocchi lunghi") },
	{ wxT("Show seconds on clock"), wxT("Mostra secondi sull'orologio") },
	{ wxT("Italian signals"), wxT("Segnali italiani") },
	{ wxT("Hard performance tracking"), wxT("Controllo stretto prestazioni") },
	{ wxT("Save preferences on exit"), wxT("Salva preferenze in uscita") },
    { wxT("Change your preferences and click \"Update\"..."), wxT("Scegli le preferenze e clicca su \"Aggiorna\"...") },

	{ wxT("Itinerary"), wxT("Itinerari") },
	{ wxT("Name :"), wxT("Nome :") },
	{ wxT("From signal '%s'"), wxT("Dal segnale '%s'") },
	{ wxT("Next itinerary :"), wxT("Prossimo itinerario") },

	{ wxT("Performance status"), wxT("Sommario prestazione") },
	{ wxT("Wrong destinations :"), wxT("Destinazioni sbagliate :") },
	{ wxT("Late trains :"), wxT("Treni in ritardo :") },
	{ wxT("Thrown switches :"), wxT("Scambi girati inutilmente :") },
	{ wxT("Cleared signals :"), wxT("Segnali aperti inutilmente :") },
	{ wxT("Turned trains :"), wxT("Inversioni di direzione inutili :") },
	{ wxT("Trains stopped at sig.:"), wxT("Treni fermati a segnali :") },
	{ wxT("Wrong platforms :"), wxT("Binari arrivi sbagliati :") },
	{ wxT("Commands denied :"), wxT("Ordini sbagliati :") },
	{ wxT("Wrong stock assignments :"), wxT("Assegnazioni materiali sbagliate :") },

	{ wxT("Created by"), wxT("Creato da") },
	{ wxT("This is a game, and is not intended to\nbe used to actually control train traffic."), wxT("Questo e' un gioco e non e' progettato per\nessere usato per il controllo reale del traffico ferroviario.") },
	{ wxT("This is free software, released under the\nGNU General Public License."), wxT(" Questo software e' gratis, distribuito sotto la\nGNU General Public License.") },
	{ wxT("This is free software, released under the\nGNU General Public License.\nThe author declines any responsibility for any damage\nthat might occur from the use of this program."), wxT(" Questo software e' gratis, distribuito sotto la\nGNU General Public License.\nL'autore declina ogni responsabilita' per eventuali\ndanni causati dall'uso di questo programma.") },
	{ wxT("This is free software, released under the\nGNU General Public License Version 2.\nThe author declines any responsibility for any damage\nthat might occur from the use of this program."), wxT(" Questo software e' gratis, distribuito sotto la\nGNU General Public License.\nL'autore declina ogni responsabilita' per eventuali\ndanni causati dall'uso di questo programma.") },

	{ wxT("Layout Errors"), wxT("Errori nel tracciato") },
	{ wxT("These trains will be delayed on entry:"), wxT("Questi treni saranno ritardati in ingresso:") },
	{ wxT("%s and %s both enter at %s on %s"), wxT("Sia %s che %s entrano a %s alle %s") },
	{ wxT("These trains have unknown entry or exit points:"), wxT("Questi treni non hanno un punto di ingresso o uscita conosciuto") },
	{ wxT("%s enters from '%s', exits at '%s'"), wxT("'%s' entra da '%s', esce a '%s'") },

	{ wxT("Some train has unknown entry/exit point!"), wxT("Qualche treno ha un punto di ingresso/uscita sconosciuto!") },
	{ wxT("at"), wxT("a") },


	{ wxT("Start"), wxT("Partenza") },
	{ wxT("Fast"), wxT("Veloce") },
	{ wxT("Slow"), wxT("Lento") },
	{ wxT("Sched."), wxT("Orario") },

	{ wxT("Simulation results"), wxT("Risultati della simulazione") },
	{ wxT("Time"), wxT("Tempo") },
	{ wxT("Total points"), wxT("Punteggio totale") },
	{ wxT("Total min. of delayed entry"), wxT("Minuti totali di ingressi ritardati") },
	{ wxT("Total min. trains arrived late"), wxT("Minuti totali di treni arrivati in ritardo") },
	{ wxT("Total performance penalties"), wxT("Penalita' totali") },
	{ wxT("Wrong destinatios"), wxT("Destinazioni sbagliate") },
	{ wxT("Late trains"), wxT("Treni in ritardo") },
	{ wxT("Wrong platforms"), wxT("Binari di arrivo sbagliati") },
	{ wxT("Commands denied"), wxT("Ordini sbagliati") },
	{ wxT("Trains waiting at signals"), wxT("Treni fermati a segnali") },
	{ wxT("Thrown switches"), wxT("Scambi girati inutilmente") },
	{ wxT("Cleared signals"), wxT("Segnali aperti inutilmente") },
	{ wxT("Wrong stock assignments"), wxT("Assegnazioni materiali sbagliate") },
	{ wxT("Reversed trains"), wxT("Inversione di direzione inutili") },
	{ wxT("Save as text"), wxT("Salva come file testo") },
	{ wxT("(hide canceled trains)"), wxT("(nascondi treni non circolanti)") },
	{ wxT("(show canceled trains)"), wxT("(mostra treni non circolanti)") },

	{ wxT("Enters"), wxT("Ingresso") },
	{ wxT("At"), wxT("Alle") },
	{ wxT("Exits"), wxT("Uscita") },
	{ wxT("Before"), wxT("per le") },
	{ wxT("Delay"), wxT("Ingr.ritardato") },
	{ wxT("Late"), wxT("Ritardo") },
	{ wxT("Status"), wxT("Stato") },

	{ wxT("Station"), wxT("Stazione") },
	{ wxT("Arrival"), wxT("Arrivo") },
	{ wxT("Departure"), wxT("Partenza") },
	{ wxT("Min.stop"), wxT("Minuti di stop") },
	{ wxT("Plat."), wxT("Binario") },
	{ wxT("Runs on"), wxT("Circola i") },
	{ wxT("Notes"), wxT("Note") },
	{ wxT("To&nbsp;&nbsp;"), wxT("Per&nbsp;&nbsp;") },
	{ wxT("To&nbsp;&nbsp;&nbsp;"), wxT("Per&nbsp;&nbsp;&nbsp;") },
	{ wxT("Runs on&nbsp;&nbsp;"), wxT("Circola i&nbsp;") },
	{ wxT("Runs&nbsp;on&nbsp;&nbsp;"), wxT("Circola&nbsp;i&nbsp;") },
	{ wxT("Minimum stop (sec)"), wxT("Attesa minima (sec)") },

	{ wxT("Territory"), wxT("Territorio") },

	{ wxT("Are you sure you want to restore\nthe simulation to its saved state?"), wxT("Ripartire dall'ora iniziale del salvataggio?") },
	{ wxT("This will delete the current layout.\nAre you sure you want to continue?"), wxT("Quest'azione cancella il tracciato.\nSei sicuro di voler continuare?") },
	{ wxT("Replay interrupted."), wxT("Replay interrotto.") },


	{ wxT("/File/Open recent"), wxT("/File/Apri recenti") },

	{ wxT("Train %s waiting at %d,%d!"), wxT("Treno %s fermo a %d,%d!") },
	{ wxT("Train %s waiting at"), wxT("Treno %s fermo a") },
	{ wxT("You must assign train %s using stock from train %s!"), wxT("Devi assegnare il treno %s usando il materiale dal treno %s!") },
	{ wxT("Train %s derailed at %s!"), wxT("Treno %s deragliato a %s!") },
	{ wxT("Train %s derailed at %d,%d!"), wxT("Treno %s deragliato a %d,%d!") },
	{ wxT("Train %s derailed!"), wxT("Treno %s deragliato") },
	{ wxT("Train %s delayed at %s!"), wxT("Treno %s in ritardo a %s!") },
	{ wxT("Cannot reverse direction. Path is busy."), wxT("Impossibile invertire la direzione. Binario occupato.") },
	{ wxT("This signal cannot be turned to green!"), wxT("Impossibile porre questo segnale a verde!") },
	{ wxT("You must wait for train to stop."), wxT("Devi attendere che il treno sia fermo.") },
	{ wxT("Reverse train direction?"), wxT("Invertire la direzione del treno?") },
	{ wxT("Proceed to next station?"), wxT("Avanzare il treno fino alla prossima stazione?") },

	{ wxT("Sorry, this feature is not available on this scenario."), wxT("Spiacente, ma questa funzione non e' disponibile in questo scenario.") },
	{ wxT("No station has distance information."), wxT("Nessuna stazione ha informazioni sulle progressive chilometriche.") },
	{ wxT("Train Schedule Graph"), wxT("Grafico Orario") },

	{ wxT("Error reading"), wxT("Errore nella lettura di") },
	{ wxT("Final stop"), wxT("Ultima fermata") },
	{ wxT("at"), wxT("alle") },
	{ wxT("Next stop"), wxT("Prossima fermata") },
	{ wxT("ready"), wxT("pronto") },
	{ wxT("Canceled - runs on"), wxT("Soppresso - circola il") },
	{ wxT("Shunting"), wxT("Manovra") },
	{ wxT("to"), wxT("per") },
	{ wxT("Running. Dest."), wxT("In movimento. Dest.") },
	{ wxT("Stopped. ETD"), wxT("Fermo. Parte alle") },
	{ wxT("Dest."), wxT("Dest.") },
	{ wxT("Delayed entry at"), wxT("Ingresso ritardato a") },
	{ wxT("Starting"), wxT("In avvio") },
	{ wxT("Waiting"), wxT("In attesa") },
	{ wxT("derailed"), wxT("deragliato") },
	{ wxT("Arrived at"), wxT("Arrivato a") },
	{ wxT("instead of"), wxT("invece che a") },
	{ wxT("Arrived"), wxT("Arrivato con") },
	{ wxT("min. late at"), wxT("min. di ritardo a") },
	{ wxT("Arrived on time"), wxT("Arrivato in orario") },
	{ wxT("stock for"), wxT("materiale per") },

	{ wxT("Signal at"), wxT("Segnale a") },
	{ wxT("not linked to any track"), wxT("non collegato ad alcun binario") },
	{ wxT("Track at"), wxT("Binario a") },
	{ wxT("not controlled by signal at"), wxT("non controllato dal segnale a") },
	{ wxT("linked to non-existant track at"), wxT("collegato a binario inesistente a") },
	{ wxT("not linked back to"), wxT("non ricollegato al binario a") },
	{ wxT("Switch at"), wxT("Scambio a") },
	{ wxT("linked to non-existant switch at"), wxT("collegato a scambio inesistente a") },
	{ wxT("not linked back to switch at"), wxT("non ricollegato allo scambio a") },
	{ wxT("Checking for errors in layout...\n"), wxT("Controllo errorin nel tracciato...\n") },
	{ wxT("nly like tracks can be linked."), wxT("Solo binari compatibili possono essere collegati.") },
	{ wxT("Only horizontal or vertical tracks can be linked automatically.\nTo link other track types, use the track properties dialog."), wxT("Solo binari orizzontali o verticali possono essere collegati automaticamente. Per collegare altri tipo di binario, usare il dialogo delle proprieta'.") },
	{ wxT("Signals can only be linked to a track."), wxT("Un segnale puo' solo essere collegato a un binario.") },
	{ wxT("Triggers can only be linked to a track."), wxT("Un pedale puo' solo essere collegato a un binario.") },
	{ wxT("Entry/Exit point can only be linked to a track."), wxT("Un punto di ingresso/uscita puo' solo essere collegato a un binario.") },

	{ wxT("speed"), wxT("veloc.") },
	{ wxT("length"), wxT("lungh.") },
	{ wxT("Station"), wxT("Stazione") },
	{ wxT("entry/exit"), wxT("ingresso/uscita") },
	{ wxT("Signal"), wxT("Segnale") },
	{ wxT("controls"), wxT("controlla") },

	{ wxT("Station of"), wxT("Stazione di") },
	{ wxT("Platform"), wxT("Binario") },
	{ wxT("An itinerary by the same name already exists.\nDo you want to replace the old itinerary with the new one?"), wxT("Un itinerarion con lo stesso nome esiste gia'.\nLo vuoi rimpiazzare con quello nuovo?") },

	{ wxT("Cannot create log file."), wxT("Impossibile create il file di log.") },
	{ wxT("Cannot read log file."), wxT("Impossibile leggere il file di log.") },
	{ wxT("Do you want to restart the simulation?"), wxT("Vuoi far ripartire la simulazione dall'inizio?") },
	{ wxT("Simulation restarted."), wxT("Simulazione ritornata alle condizioni iniziali.") },

	{ wxT("Stop"), wxT("Stop") },
	{ wxT("Start"), wxT("Parti") },
	{ wxT("Restart"), wxT("Riparti") },
	{ wxT("Layout saved in file"), wxT("Tracciato salvato nel file") },
	{ wxT("Game status saved in file"), wxT("Stato del gioco salvato nel file") },
	{ wxT("No schedule for this territory!"), wxT("Orario inesistente per questo tracciato!") },
	{ wxT("Question"), wxT("Domanda") },
	{ wxT("Warning"), wxT("Attenzione") },
	{ wxT("Attention"), wxT("Errore") },
	{ wxT("Open File"), wxT("Apri file") },
	{ wxT("Error"), wxT("Errore") },
	{ wxT("Scenarios"), wxT("Scenari") },
	{ wxT("Saved games"), wxT("Partite salvate") },
	{ wxT("All files (*.*)"), wxT("Tutti i files (*.*)") },
	{ wxT("Icons"), wxT("Icone") },
	{ wxT("Save File"), wxT("Salva File") },
	{ wxT("Can't create file"), wxT("Impossibile creare il file") },
        { wxT("Platform Graph"), wxT("Grafico Binari") },
        { wxT("&Platform Graph"), wxT("Grafico &Binari") },
        { wxT("Show platforms occupancy over time."), wxT("Mostra l'occupazione dei binari durante la giornata.") },

	{ wxT("/_File"), wxT("/_File") },
	{ wxT("/File/_Open"), wxT("/File/_Apri") },
	{ wxT("/File/Open re_cent"), wxT("/File/Apri re_cente") },
	{ wxT("/File/_Save Game"), wxT("/File/_Salva Gioco") },
	{ wxT("/File/_Restore"), wxT("/File/_Recupera") },
	{ wxT("/File/Save _As"), wxT("/File/Salva _Come") },
	{ wxT("/File/_Log"), wxT("/File/Re_gistra") },
	{ wxT("/File/_Replay"), wxT("/File/_Replay") },
	{ wxT("/File/About..."), wxT("/File/Informazioni...") },
	{ wxT("/File/Quit"), wxT("/File/Uscita") },
	{ wxT("/Edit/_Edit"), wxT("/Edit/_Edit") },
	{ wxT("/Edit/_New Train"), wxT("/Edit/_Nuovo Treno") },
	{ wxT("/Edit/Itinerary"), wxT("/Edit/Itinerario") },
	{ wxT("/Edit/_Save Layout"), wxT("/Edit/_Salva Tracciato") },
	{ wxT("/Edit/_Preferences"), wxT("/Edit/_Preferenze") },
	{ wxT("/Edit/_New"), wxT("/Edit/_Nuovo Tracciato") },
	{ wxT("/Edit/_Info"), wxT("/Edit/_Informazioni") },
	{ wxT("/_Run"), wxT("/_Simula") },
	{ wxT("/Run/_Start"), wxT("/Simula/_Parti") },
	{ wxT("/Run/View _Graph"), wxT("/Simula/Orario _Grafico") },
	{ wxT("/Run/Restart"), wxT("/Simula/Riparti") },
	{ wxT("/Run/_Fast"), wxT("/Simula/_Veloce") },
	{ wxT("/Run/S_low"), wxT("/Simula/_Lento") },
	{ wxT("/Run/S_tation schedule"), wxT("/Simula/Orario di _Stazione") },
	{ wxT("/Run/Set sig. to green"), wxT("/Simula/Segnali autom. a verde") },
	{ wxT("/Run/Performance"), wxT("/Simula/Prestazioni") },

	{ wxT("# about dialog"), wxT("Informazioni") },

	{ wxT("This is a game, and is not intended to\nbe used to actually control train traffic."), wxT("Questo programma e' un gioco, e non e' stato\nprogettato per il controllo del traffico ferroviario reale.") },
	{ wxT("This is free software, released under the\nGNU General Public License 2."), wxT("Questo software e' gratis,\ndistribuito sotto la GNU General Public License 2.") },
	{ wxT("The author declines any responsibility for any damage\nthat might occur from the use of this program."), wxT("L'autore declina ogni responsabilita' per eventuali\ndanni causati dall'uso di questo programma.") },

	{ wxT("Assign rolling stock"), wxT("Assegnazione materiale rotabile") },
	{ wxT("&Assign"), wxT("&Assegna") },
	{ wxT("S&hunt"), wxT("&Manovra") },
	{ wxT("Sp&lit"), wxT("Spe&zza") },
	{ wxT("&Properties"), wxT("&Proprieta'") },
	{ wxT("&Cancel"), wxT("&Cancella") },
        { wxT("Start Now"), wxT("Partenza Immediata") },

	{ wxT("Itinerary definition"), wxT("Definizione itinerari") },
	{ wxT("&Name"), wxT("Nome") },
	{ wxT("From signal"), wxT("Dal segnale") },
	{ wxT("Ne&xt itinerary"), wxT("&Prossimo itinerario") },

	{ wxT("Performance"), wxT("Prestazione") },
	{ wxT("Count"), wxT("Frequenza") },
	{ wxT("Points"), wxT("Penalita'") },
	{ wxT("Total"), wxT("Totale") },
	{ wxT("Wrong destinations"), wxT("Destinazioni sbagliate") },
	{ wxT("Late trains"), wxT("Treni arrivati in ritardo") },
	{ wxT("Wrong platforms"), wxT("Binari sbagliati") },
	{ wxT("Commands denied"), wxT("Ordini sbagliati") },
	{ wxT("Trains stopped at signals"), wxT("Treni fermati a segnali") },
	{ wxT("Turned trains"), wxT("Inversioni di direzione inutili") },
	{ wxT("Thrown switches"), wxT("Scambi girati inutilmente") },
	{ wxT("Cleared signals"), wxT("Segnali messi a verde inutilmente") },
	{ wxT("Wrong stock assignments"), wxT("Assegnazioni materiale sbagliate") },


	{ wxT("Preferences"), wxT("Preferenze") },
        { wxT("Options"), wxT("Opzioni") },
	{ wxT("Short train info"), wxT("Informazioni treni ridotte") },
	{ wxT("Status line at top of window"), wxT("Linea di stato in alto") },
	{ wxT("Alert sound on"), wxT("Suono di avviso abilitato") },
	{ wxT("Alert on train entering layout"), wxT("Avviso sonoro su ingresso treno nel tracciato") },
	{ wxT("View speed limits"), wxT("Mostra i punti di cambio velocita'") },
	{ wxT("Automatically link signals"), wxT("Collega automaticamente i segnali") },
        { wxT("Link signals to left track"), wxT("Collega i segnali al binario alla loro sinistra") },
	{ wxT("Show grid"), wxT("Mosta griglia") },
	{ wxT("View long blocks"), wxT("Mostra i binari lunghi") },
	{ wxT("Show seconds on clock"), wxT("Mostra i secondi sull'orologio") },
	{ wxT("Traditional signals"), wxT("Segnali tradizionali") },
	{ wxT("Strong performance checking"), wxT("Controllo piu' restrittivo sugli errori") },
	{ wxT("Show linked objects in editor"), wxT("Mostra i collegamenti degli oggetti nell'editor") },
        { wxT("Show scripted objects in editor"), wxT("Mostra gli oggetti con script nell'editor") },
	{ wxT("Show trains icons"), wxT("Mostra le icone dei treni") },
	{ wxT("Show trains tooltip"), wxT("Mostra il \"tooltip\" per i treni") },
        { wxT("Enable random delays"), wxT("Abilita ritardi casuali") },
        { wxT("Wait while playing sounds"), wxT("Blocca la simulazione durante i suoni") },
	{ wxT("Check the desired options:"), wxT("Selezionare le opzioni desiderate:") },

        { wxT("Environment"), wxT("Ambiente") },
        { wxT("Path to sound file for alert notifications"), wxT("Percorso del file suono degli avvisi") },
        { wxT("Path to sound file for train entry"), wxT("Percorso del file suono per l'ingresso treni") },
        { wxT("Directories with signal scripts"), wxT("Directory con script segnali") },

        { wxT("Background"), wxT("Sfondo") },
        { wxT("Free Track"), wxT("Binario Libero") },
        { wxT("Reserved Track"), wxT("Binario Riservato") },
        { wxT("Reserved for Shunting"), wxT("Binario Riservato per Manovra") },
        { wxT("Occupied"), wxT("Occupato") },
        { wxT("Reserved for Working"), wxT("Riservato per Lavori") },
        { wxT("Switch Outline"), wxT("Contorno Scambi") },
        { wxT("Text"), wxT("Testo") },
        { wxT("Color..."), wxT("Colore...") },

        { wxT("Enable HTTP server"), wxT("Abilita il server HTTP") },
        { wxT("HTTP Server Port"), wxT("Porta Server HTTP") },
        { wxT("User name"), wxT("Nome utente") },

	{ wxT("Scenario Information"), wxT("Informazioni Scenario") },

	{ wxT("Day selection"), wxT("Selezione giorno") },
	{ wxT("&Continue"), wxT("&Continua") },

	{ wxT("Signal at coordinates :"), wxT("Segnale alle coordinate :") },
	{ wxT("Signal name :"), wxT("Nome segnale") },
	{ wxT("Linked to east :"), wxT("Linkato a est :") },
	{ wxT("Linked to west :"), wxT("Linkato a ovest :") },
	{ wxT("Signal is always red"), wxT("Segnale sempre al rosso") },
	{ wxT("Signal has square frame"), wxT("Segnale a vela quadra") },
	{ wxT("No penalty for train stopping at this signal"), wxT("Nessuna penalita' se un treno si ferma a questo segnale") },

	{ wxT("Station schedule"), wxT("Orario di stazione") },
	{ wxT("S&tation schedule\tF5"), wxT("Orario di s&tazione\tF5") },
	{ wxT("&Schedule for station :"), wxT("&Orario per la stazione di :") },
	{ wxT("&Ignore platform number"), wxT("&Ignora il binario di arrivo") },
	{ wxT("&Close"), wxT("&Chiudi") },
	{ wxT("&Print"), wxT("&Stampa") },

	{ wxT("Layout Information"), wxT("Informazioni sul tracciato") },

	{ wxT("Track Properties"), wxT("Proprieta' del binario") },
	{ wxT("Track Length (m) :"), wxT("Lunghezza binario (m) :") },
	{ wxT("Station name :"), wxT("Nome stazione :") },
	{ wxT("Switch name :"), wxT("Nome scambio :") },
        { wxT("Speed(s) :"), wxT("Velocita' :") },
        { wxT("Branch Speed(s) :"), wxT("Velocita' in deviata :") },

	{ wxT("Train Properties"), wxT("Proprieta' del treno") },
	{ wxT("Train name"), wxT("Nome treno") },
	{ wxT("Train type"), wxT("Tipo treno") },
	{ wxT("Entry point"), wxT("Punto di ingresso") },
	{ wxT("Entry time (hh:mm)"), wxT("Orario di ingresso (hh:mm)") },
	{ wxT("Exit point"), wxT("Punto di uscita") },
	{ wxT("Exit time (hh:mm)"), wxT("Orario di uscita (hh:mm)") },
	{ wxT("Wait arrival of train"), wxT("Attende l'arrivo del treno") },
	{ wxT("Stock for train"), wxT("Materiale per treno") },
	{ wxT("Runs on"), wxT("Circola il") },
	{ wxT("Train length :"), wxT("Lunghezza treno :") },

	{ wxT("Trigger Properties"), wxT("Proprieta' Pedale") },
	{ wxT("Trigger at coordinates :"), wxT("Pedale alle coordinate :") },
	{ wxT("Action\n(e.g. \"click 12,4\")"), wxT("Azione\n(es. \"click 12,4\")") },
	{ wxT("Linked to track at :"), wxT("Collegato al binario a :") },
	{ wxT("Probabilities :"), wxT("Probabilita'") },
	{ wxT("Action:             ('@' in action = name of triggering train)"), wxT("Azione: ('@' nell'azione = nome del treno attivante)") },
	{ wxT("Linked to track at coord :"), wxT("Collegato al binario alle coord. :") },
	{ wxT("Probabilities for action :"), wxT("Probabilita' per l'azione :") },

	{ wxT("cannot load"), wxT("Impossibile caricare") },
	{ wxT("Destination"), wxT("Destinazione") },
	{ wxT("Assigning stock of train %s arrived at station %s"), wxT("Assegnamento materiale treno %s arrivato a %s") },
	{ wxT("From signal '%s'"), wxT("Dal segnale '%s'") },

	{ wxT("&File"), wxT("&File") },
	{ wxT("&Open...\tCtrl-O"), wxT("&Apri...\tCtrl-O") },
	{ wxT("&Save Game..."), wxT("&Salva Gioco...") },
	{ wxT("&Restore..."), wxT("&Riparti simulazione...") },
	{ wxT("Page set&up"), wxT("Config&ura Pagina Stampa") },
	{ wxT("Pre&view"), wxT("Bo&zza di Stampa") },
	{ wxT("&Print"), wxT("Stam&pa") },
	{ wxT("&Edit"), wxT("&Edit") },
	{ wxT("&Itinerary"), wxT("&Itinerari") },
	{ wxT("&Save Layout"), wxT("&Salva Tracciato") },
	{ wxT("&Preferences..."), wxT("&Preferenze") },
	{ wxT("Exit\tAlt-F4"), wxT("Esci\tAlt-F4") },
	{ wxT("Ne&w"), wxT("&Nuovo Tracciato") },
	{ wxT("In&fo"), wxT("&Informazioni") },
	{ wxT("&Run"), wxT("&Simula") },
	{ wxT("&Start\tCtrl-S"), wxT("&Parti\tCtrl-S") },
	{ wxT("&Graph\tCtrl-G"), wxT("Orario &Grafico\tCtrl-G") },
	{ wxT("&Late Graph\tCtrl-L"), wxT("Grafico Ritardi\tCtrl-L") },
    { wxT("Late Graph"), wxT("Grafico Ritardi") },
    { wxT("Time-Distance Diagram"), wxT("Grafico Orario") },
	{ wxT("&Restart..."), wxT("&Riparti...") },
	{ wxT("&Fast\tCtrl-X"), wxT("&Veloce\tCtrl-X") },
	{ wxT("&Slow\tCtrl-Z"), wxT("&Lento\tCtrl-Z") },
	{ wxT("S&kip ahead\tCtrl-K"), wxT("Avanza Orologio\tCtrl-K") },
	{ wxT("S&tation schedule\tF6"), wxT("Orario Stazioni\tF6") },
	{ wxT("Select Itinerary\tCtrl-I"), wxT("Scelta Itinerari\tCtrl-I") },
	{ wxT("Set sig. to green"), wxT("Segnali autom. a verde") },
	{ wxT("&Performance"), wxT("Prestazioni") },

	{ wxT("&View"), wxT("&Mostra") },
	{ wxT("Show layout\tF3"), wxT("Mostra tracciato\tF3") },
	{ wxT("Show schedule\tF4"), wxT("Mostra orario\tF4") },
	{ wxT("Show info page\tF5"), wxT("Mostra pagina informazioni\tF5") },
	{ wxT("Timetable in split window"), wxT("Orario in riquadro") },
	{ wxT("Timetable in tabbed window"), wxT("Orario in pannello") },
	{ wxT("Timetable in separate window"), wxT("Orario in finestra separata") },
	{ wxT("Tool bar"), wxT("Barra strumenti") },
	{ wxT("Status bar"), wxT("Linea di stato") },
	{ wxT("Zoom in"), wxT("Ingrandisci") },
	{ wxT("Zoom out"), wxT("Rimpicciolisci") },
	{ wxT("Coord bars"), wxT("Barre coordinate") },

	{ wxT("Welcome"), wxT("Benvenuto") },
	{ wxT("Welcome\tF1"), wxT("Benvenuto\tF1") },
	{ wxT("&Help"), wxT("&Aiuto") },

	{ wxT("Tools"), wxT("Strumenti") },
	{ wxT("Graph"), wxT("Grafico") },
	{ wxT("Layout"), wxT("Tracciato") },

	{ wxT("You recently played the following simulations:<br><br>"), wxT("Scenari simulati di recente:<br><br>") },
	{ wxT("Clear"), wxT("Azzera") },

	{ wxT("Remove all alerts from this list?"), wxT("Azzera la lista degli avvertimenti?") },
	{ wxT("Show Canceled"), wxT("Mostra Cancellati") },
	{ wxT("Track First Train"), wxT("Segui Primo Treno Attivo") },
	{ wxT("Track Last Train"), wxT("Segui Ultimo Treno Attivo") },
	{ wxT("Show/hide canceled trains from list"), wxT("Mostra/nasconde dalla lista i treni che non circolano") },
	{ wxT("Automatically show first active train in list"), wxT("Mostra automaticamente nella lista il primo treno attivo") },
	{ wxT("Automatically show last active train in list"), wxT("Mostra automaticamente nella lista l'ultimo treno attivo") },
        { wxT("Set Delay"), wxT("Assegna ritardo") },
        { wxT("Force delayed entry or departure of train"), wxT("Forza un ritardo in secondi per l'ingresso o la partenza") },

	{ wxT("Stations &List"), wxT("&Lista Stazioni") },
	{ wxT("Stations and Entry/Exit Points"), wxT("Stazioni e Punti di Ingresso/Uscita") },
	{ wxT("Station Name"), wxT("Nome Stazione") },
	{ wxT("Coordinates"), wxT("Coordinate") },
	{ wxT("Entry/Exit"), wxT("Ingresso/Uscita") },
        { wxT("Blocked by :"), wxT("Bloccato da:") },

	//{ wxT("### spiegazioni delle voci di menu'") },

	{ wxT("Open a simulation file."), wxT("Apre uno scenario.") },
	{ wxT("Open a saved simulation file."), wxT("Apre uno scenario salvato precedentemente.") },
	{ wxT("Restore from the last saved state."), wxT("Ricarica l'ultimo scenario salvato.") },
	{ wxT("Changes the page layout settings."), wxT("Cambia le opzioni della pagina tracciato.") },
	{ wxT("Preview print output."), wxT("Visione bozza di stampa.") },
	{ wxT("Print all or part of the document."), wxT("Stampa tutto o parte del documento.") },
	{ wxT("Quit this program."), wxT("Esci dal programma.") },
	{ wxT("Enter/exit layout editor."), wxT("Entra/esce dall'editor del tracciato.") },
	{ wxT("Enter/exit itinerary editor."), wxT("Entra/esce dall'editor itinerari.") },
	{ wxT("Save changes to the layout."), wxT("Salva le modifiche al tracciato.") },
	{ wxT("Change program's preferences."), wxT("Modifica delle preferenze.") },
	{ wxT("Erase the layout."), wxT("Azzera il tracciato.") },
	{ wxT("Show information about the scenario."), wxT("Mostra informazioni relative allo scenario.") },
	{ wxT("Show list of stations and entry points."), wxT("Lista le stazioni e i punti di ingresso/uscita") },
	{ wxT("Start/stop the simulation."), wxT("Fa partire/ferma la simulazione.") },
	{ wxT("Show the timetable graph."), wxT("Mostra il grafico orario.") },
	{ wxT("Show accumulation of late minutes over time."), wxT("Mostra il grafico ritardi.") },
	{ wxT("Restart the simulation."), wxT("Fa ripartire la simulazione.") },
	{ wxT("Speed up the simulation."), wxT("Accelera la velocita' di simulazione.") },
	{ wxT("Slow down the simulation."), wxT("Rallenta la velocita' di simulazione.") },
	{ wxT("Skip to 3 minutes before next event."), wxT("Avanza la simulazione a 3 minuti prima del prossimo evento.") },
	{ wxT("Show the train schedule of each station."), wxT("Mostra l'orario per stazione.") },
	{ wxT("Set all automatic signals to green."), wxT("Poni tutti i segnali automatici a verde.") },
	{ wxT("Select an itinerary by name."), wxT("Sceglie un itinerario usandone il nome.") },
	{ wxT("Show performance data."), wxT("Mostra la tabella delle penalita'.") },
	{ wxT("Forcibly show the layout window."), wxT("Mostra la finestra del tracciato.") },
	{ wxT("Forcibly show the schedule window."), wxT("Mostra la finestra dell'orario.") },
	{ wxT("Shows the scenario info page, if available."), wxT("Mostra la pagina di informazioni dello scenario, se presente.") },
	{ wxT("View timetable in a split window."), wxT("Mostra l'orario in un riquadro.") },
	{ wxT("View timetable in a tab of the main window."), wxT("Mostra l'orario nella finestra principale.") },
	{ wxT("View timetable in a window separate from the main window."), wxT("Mostra l'orario in una finestra separata.") },
	{ wxT("Draw the layout at double the resolution."), wxT("Disegna il tracciato a grandezza raddoppiata.") },
	{ wxT("Draw the layour at normal resolution."), wxT("Disegna il tracciato a grandezza naturale.") },
	{ wxT("View/hide the coordinate bars."), wxT("Mostra/nasconde le barre delle coordinate.") },
	{ wxT("View/hide the tools bar."), wxT("Mostra/nasconde la barra strumenti.") },
	{ wxT("View/hide the status bar."), wxT("Mostra/nasconde la linea di stato.") },
	{ wxT("Show the welcome page."), wxT("Mostra la pagina di benvenuto.") },
	{ wxT("Show the copyright notice."), wxT("Mostra la pagina di copyright.") },
	{ wxT("Open another simulation"), wxT("Apri una nuova simulazione") },
	{ wxT("Create a new simulation"), wxT("Crea una nuova simulazione") },
	{ wxT("Select the language to be used next time Traindir is started."), wxT("Sceglie il linguaggio da usare la prossima volta che Traindir e' eseguito.") },
	{ wxT("Swap head and tail icons"), wxT("Scambia icone di testa e di coda") },
        { wxT("Cannot create directory '%s'. Try creating it manually."), wxT("Non riesco a create la directory '%s'. Prova a crearla a mano.") },
        { wxT("Show train names instead of icons"), wxT("Mostra i nomi dei treni al posto delle icone") },
        { wxT("Don't show train names colors"), wxT("Non usare i colori nei nomi dei treni") },

        { wxT("Switch&board"), wxT("Pulsantiera") },
        { wxT("Shows the switchboard editor."), wxT("Mostra l'editor delle pulsantiere.") },
        { wxT("Switchboard"), wxT("Pulsantiera") },
        { wxT("Use this screen to define the layout of a switchboard and which itineraries are shown in it."), wxT("Usa questo schermo per definire la disposizione delle pulsantiere e quali itinerari mostrare.") },
        { wxT("Switchboards are accessed via an external web browser at the port"), wxT("Le pulsantiere sono accessibili da un browser esterno alla porta") },
        { wxT("Open the switchboard in a browser."), wxT("Apri la pulsantiera in un browser") },
        { wxT("Switchboards"), wxT("Pulsantiere") },
        { wxT("change"), wxT("cambia") },
        { wxT("New board"), wxT("Nuova pulsantiera") },
        { wxT("No selected switchboard."), wxT("Nessuna pulsantiera selezionata.") },
        { wxT("Switchboard Name"), wxT("Nome Pulsantiera") },
        { wxT("&Visible Name:"), wxT("Nome &Visibile:") },
        { wxT("&File name:"), wxT("Nome &File:") },
        { wxT("&Remove"), wxT("&Rimuovi") },
        { wxT("&Save"), wxT("&Salva") },
        { wxT("&Label"), wxT("&Dicitura") },
        { wxT("&Itinerary Name"), wxT("Nome &Itinerario") },
        { wxT("Open in external web browser"), wxT("Apri in un browser web esterno") },
        { wxT("Enable remote layout control"), wxT("Abilita visione remota del tracciato") },
        { wxT("Don't use colors when showing train names"), wxT("Non usare colori per i nomi dei treni") },
        { wxT("Use small font for train names"), wxT("Mostra i nomi dei treni con caratteri piccoli") },
        { wxT("Don't draw a box as background for train names"), wxT("Non usare uno sfondo pieno per i nomi dei treni") },
        { wxT("Play a sound on alerts"), wxT("Avviso sonoro su eventi") },
        { wxT("There are no switchboards defined for this simulation"), wxT("Non ci sono pulsantiere associate a questa simulazione") },

        { wxT("Scenario Info"), wxT("Informazioni Scenario") },
        { wxT("Saving now will lead to an invalid file. Please continue the simulation for a bit and try again."),
          wxT("Salvare ora condurrebbe a un file errato. Si prega continuare la simulazione e riprovare piu' avanti.") },
        { wxT("Final destination"), wxT("Destinazione finale") },
        { wxT("Last on Top"), wxT("Ultimo in cima") },
        { wxT("Show last alert message at the top of the view"), wxT("Mostra l'ultimo avviso in cima alla lista") },

        { wxT("No information available"), wxT("Nessuna informazione disponibile") },
        { wxT("block length"), wxT("lunghezza blocco") },
        { wxT("aspect"), wxT("aspetto") },
        { wxT("script"), wxT("scritto") },

        { wxT("&Reverse+Assign"), wxT("Inve&rti+Assegna") },
        { wxT("Assign&+Shunt"), wxT("Assegna&+Manovra") },
        { wxT("Show Arrived"), wxT("Mostra Arrivati") },

        { wxT("Max. speed :"), wxT("Vel. massima :") },

        { wxT("Entrance/departure delay (in minutes)"), wxT("Minuti di ritardo") },
        { wxT("Train %s enters from %s at %s."), wxT("Il treno %s entra da %s alle %s.") },
        { wxT("Train %s departs from %s at %s."), wxT("Il treno %s parte da %s alle %s.") },
        { wxT("\nDelay minutes to add to schedule?"), wxT("\nMinuti di ritardo?") },

	{ 0 }
};

