# =========================================================================
#     This makefile was generated by
#     Bakefile 0.1.9 (http://bakefile.sourceforge.net)
#     Do not modify, all changes will be overwritten!
# =========================================================================




prefix = /usr/local
exec_prefix = ${prefix}
INSTALL = /usr/bin/install -c
EXEEXT = 
RESCOMP = 
SETFILE = 
NM = nm
srcdir = .
top_srcdir = 
top_builddir = 
LDFLAGS_GUI = 
CXX = g++
#CXXFLAGS = -g -O0 -pthread -Wall -Wundef -Wno-ctor-dtor-privacy -finput-charset=ISO-8859-1
CXXFLAGS = -O2 -pthread -Wall -Wundef -Wno-ctor-dtor-privacy -finput-charset=ISO-8859-1
#CPPFLAGS = -D__WXDEBUG__  -DGTK_NO_CHECK_CASTS -pthread -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -DwxUSE_UNICODE=1 -I.
CPPFLAGS = -DGTK_NO_CHECK_CASTS -pthread -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D_LARGEFILE_SOURCE=1 -DwxUSE_UNICODE=1 -I.  -I/usr/include/wx-2.8 -I/usr/lib/wx/include/gtk2-unicode-release-2.8
LDFLAGS = -pthread   -L/usr/X11R6/lib 
WX_LIB_FLAVOUR = 
TOOLKIT = GTK
TOOLKIT_LOWERCASE = gtk
TOOLKIT_VERSION = 2
EXTRALIBS = -pthread   -L/usr/X11R6/lib -lz -ldl -lm 
EXTRALIBS_GUI = -Wl,--export-dynamic -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lm -lpangoxft-1.0 -lpangox-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -ldl -lgthread-2.0 -lglib-2.0 -lXinerama -lXxf86vm -lpng -lz -ljpeg -ltiff
EXTRALIBS_SDL = 
HOST_SUFFIX = 
SAMPLES_RPATH_FLAG = -Wl,-rpath,$(top_builddir)lib
SAMPLES_RPATH_POSTLINK = 

### Variables: ###

DESTDIR = 
OBJDIR = objs/
WX_RELEASE = 2.8
WX_VERSION = $(WX_RELEASE).4
LIBDIRNAME = $(top_builddir)lib
GRID_CXXFLAGS = -D__WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p) \
	$(__EXCEPTIONS_DEFINE_p) $(__RTTI_DEFINE_p) $(__THREAD_DEFINE_p) \
	-I$(srcdir) $(__DLLFLAG_p) -I$(srcdir)/../../samples $(CPPFLAGS) $(CXXFLAGS)
GRID_OBJECTS =  \
	$(__td3_os2_lib_res) \
	$(OBJDIR)Canvas.o \
	$(OBJDIR)html.o \
	$(OBJDIR)ItineraryView.o \
	$(OBJDIR)loadsave.o \
	$(OBJDIR)Main.o \
	$(OBJDIR)MainFrm.o \
	$(OBJDIR)run.o \
	$(OBJDIR)ReportBase.o \
	$(OBJDIR)TConfig.o \
	$(OBJDIR)TDFile.o \
	$(OBJDIR)GraphView.o \
	$(OBJDIR)HtmlView.o \
	$(OBJDIR)ToolsView.o \
	$(OBJDIR)TimeTblView.o \
	$(OBJDIR)track.o \
	$(OBJDIR)trsim.o \
	$(OBJDIR)NotebookMgr.o \
	$(OBJDIR)AlertList.o \
	$(OBJDIR)AssignDialog.o \
	$(OBJDIR)DaysDialog.o \
	$(OBJDIR)ItineraryDialog.o \
	$(OBJDIR)ConfigDialog.o \
	$(OBJDIR)OptionsDialog.o \
	$(OBJDIR)SignalDialog.o \
	$(OBJDIR)TrackDialog.o \
	$(OBJDIR)TriggerDialog.o \
	$(OBJDIR)TrainInfoDialog.o \
	$(OBJDIR)StationInfoDialog.o \
	$(OBJDIR)TrainInfoList.o \
	$(OBJDIR)TSignal.o \
	$(OBJDIR)tdscript.o \
	$(OBJDIR)ScenarioInfoDialog.o \
	$(__td3___win32rc)

### Conditionally set variables: ###

CXXC = $(CXX)
#CXXC = $(top_builddir)./bk-deps $(CXX)
PLUGIN_ADV_EXTRALIBS = $(EXTRALIBS_SDL)
#PORTNAME = base_net
PORTNAME = $(TOOLKIT_LOWERCASE)$(TOOLKIT_VERSION)
#WXBASEPORT = _carbon
#WXDEBUGFLAG = d
#WXDEBUGFLAG = d
WXUNICODEFLAG = u
#WXUNIVNAME = univ
EXTRALIBS_FOR_BASE = $(EXTRALIBS)
#EXTRALIBS_FOR_BASE = $(EXTRALIBS) $(EXTRALIBS_GUI)
EXTRALIBS_FOR_GUI = $(EXTRALIBS_GUI)
#EXTRALIBS_FOR_GUI = 
#__td3___mac_setfilecmd = \
#	$(SETFILE) -a C td3$(EXEEXT)
#__td3___mac_rezcmd = $(__MACOSX_RESOURCES_p_1)
#__WXUNIV_DEFINE_p = -D__WXUNIVERSAL__
#__WXUNIV_DEFINE_p_1 = -d __WXUNIVERSAL__
#__WXUNIV_DEFINE_p_2 = --define __WXUNIVERSAL__
#__EXCEPTIONS_DEFINE_p = -DwxNO_EXCEPTIONS
#__EXCEPTIONS_DEFINE_p_1 = -d wxNO_EXCEPTIONS
#__EXCEPTIONS_DEFINE_p_2 = --define wxNO_EXCEPTIONS
#__RTTI_DEFINE_p = -DwxNO_RTTI
#__RTTI_DEFINE_p_1 = -d wxNO_RTTI
#__RTTI_DEFINE_p_2 = --define wxNO_RTTI
#__THREAD_DEFINE_p = -DwxNO_THREADS
#__THREAD_DEFINE_p_1 = -d wxNO_THREADS
#__THREAD_DEFINE_p_2 = --define wxNO_THREADS
__DLLFLAG_p = -DWXUSINGDLL
__DLLFLAG_p_1 = -d WXUSINGDLL
__DLLFLAG_p_2 = --define WXUSINGDLL
COND_PLATFORM_OS2_1___td3___os2_emxbindcmd = $(NM) td3$(EXEEXT) | if grep -q \
	pmwin.763 ; then emxbind -ep td3$(EXEEXT) ; fi
#__td3___os2_emxbindcmd = $(COND_PLATFORM_OS2_1___td3___os2_emxbindcmd)
#__td3_os2_lib_res = \
#	$(top_srcdir)/include/wx/os2/wx.res
#__td3_bundle___depname = td3_bundle
#____td3_BUNDLE_TGT_REF_DEP = td3.app/Contents/PkgInfo
#____td3_BUNDLE_TGT_REF_DEP = td3.app/Contents/PkgInfo
COND_MONOLITHIC_0___WXLIB_ADV_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)_adv-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_ADV_p = $(COND_MONOLITHIC_0___WXLIB_ADV_p)
COND_MONOLITHIC_0___WXLIB_CORE_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)_core-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_CORE_p = $(COND_MONOLITHIC_0___WXLIB_CORE_p)
COND_MONOLITHIC_0___WXLIB_BASE_p = \
	-lwx_base$(WXBASEPORT)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_BASE_p = $(COND_MONOLITHIC_0___WXLIB_BASE_p)
COND_MONOLITHIC_0___WXLIB_BASE_NET_p = \
	-lwx_base_net$(WXBASEPORT)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_BASE_NET_p = $(COND_MONOLITHIC_0___WXLIB_BASE_NET_p)
#__td3___win32rc = CCommandView.o
COND_MONOLITHIC_1___WXLIB_MONO_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
COND_MONOLITHIC_0___WXLIB_FL_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)_fl-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_FL_p = $(COND_MONOLITHIC_0___WXLIB_FL_p)
COND_MONOLITHIC_0___WXLIB_HTML_p = \
	-lwx_$(PORTNAME)$(WXUNIVNAME)$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)_html-$(WX_RELEASE)$(HOST_SUFFIX)
__WXLIB_HTML_p = $(COND_MONOLITHIC_0___WXLIB_HTML_p)
#__WXLIB_MONO_p = $(COND_MONOLITHIC_1___WXLIB_MONO_p)
#__LIB_TIFF_p \
#	= \
#	-lwxtiff$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_JPEG_p \
#	= \
#	-lwxjpeg$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_PNG_p \
#	= \
#	-lwxpng$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_ZLIB_p = \
#	-lwxzlib$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_ODBC_p = \
#	-lwxodbc$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
COND_WXUSE_REGEX_BUILTIN___LIB_REGEX_p = \
	-lwxregex$(WXUNICODEFLAG)$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
#__LIB_REGEX_p = $(COND_WXUSE_REGEX_BUILTIN___LIB_REGEX_p)
#__LIB_EXPAT_p = \
#	-lwxexpat$(WXDEBUGFLAG)$(WX_LIB_FLAVOUR)-$(WX_RELEASE)$(HOST_SUFFIX)
COND_TOOLKIT_MAC___MACOSX_RESOURCES_p_1 = $(RESCOMP) -d __DARWIN__ -t APPL -d \
	__WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p_1) $(__EXCEPTIONS_DEFINE_p_1) \
	$(__RTTI_DEFINE_p_1) $(__THREAD_DEFINE_p_1) -i $(srcdir) $(__DLLFLAG_p_1) -i \
	$(srcdir)/../../samples -i $(top_srcdir)/include -o td3$(EXEEXT) Carbon.r \
	sample.r
#__MACOSX_RESOURCES_p_1 = $(COND_TOOLKIT_MAC___MACOSX_RESOURCES_p_1)

### Targets: ###

all: traindir3$(EXEEXT) $(__td3_bundle___depname)

install: all

uninstall: 

install-strip: install

clean: 
	rm -rf ./.deps ./.pch
	rm -f $(OBJDIR)*.o
	rm -f traindir3$(EXEEXT)
	rm -rf td3.app

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

traindir3$(EXEEXT): $(GRID_OBJECTS) $(__td3___win32rc)
	$(CXX) -o $@ $(GRID_OBJECTS) $(LDFLAGS)   -L$(LIBDIRNAME) $(LDFLAGS_GUI) $(SAMPLES_RPATH_FLAG)  $(__WXLIB_ADV_p) $(__WXLIB_HTML_p) $(PLUGIN_ADV_EXTRALIBS) $(__WXLIB_CORE_p)  $(__WXLIB_BASE_p)  $(__WXLIB_MONO_p) $(__LIB_TIFF_p) $(__LIB_JPEG_p) $(__LIB_PNG_p) $(__LIB_ZLIB_p) $(__LIB_ODBC_p) $(__LIB_REGEX_p) $(__LIB_EXPAT_p) $(EXTRALIBS_FOR_BASE) $(EXTRALIBS_FOR_GUI)
	$(__td3___mac_rezcmd)
	$(__td3___mac_setfilecmd)
	$(__td3___os2_emxbindcmd)
	$(SAMPLES_RPATH_POSTLINK)

td3.app/Contents/PkgInfo: td3$(EXEEXT) $(top_srcdir)/src/mac/carbon/Info.plist.in $(top_srcdir)/src/mac/carbon/wxmac.icns
	mkdir -p td3.app/Contents
	mkdir -p td3.app/Contents/MacOS
	mkdir -p td3.app/Contents/Resources
	
	
	sed -e "s/IDENTIFIER/`echo $(srcdir) | sed -e 's,\.\./,,g' | sed -e 's,/,.,g'`/" \
	-e "s/EXECUTABLE/td3/" \
	-e "s/VERSION/$(WX_VERSION)/" \
	$(top_srcdir)/src/mac/carbon/Info.plist.in >td3.app/Contents/Info.plist
	
	
	echo -n "APPL????" >td3.app/Contents/PkgInfo
	
	
	ln -f td3$(EXEEXT) td3.app/Contents/MacOS/td3
	
	
	cp -f $(top_srcdir)/src/mac/carbon/wxmac.icns td3.app/Contents/Resources/wxmac.icns

#td3_bundle: $(____td3_BUNDLE_TGT_REF_DEP)

$(OBJDIR)Canvas.o: Canvas.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) Canvas.cpp

$(OBJDIR)html.o: html.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) html.cpp

$(OBJDIR)AlertList.o: AlertList.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) AlertList.cpp

$(OBJDIR)TrainInfoList.o: TrainInfoList.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TrainInfoList.cpp

$(OBJDIR)AssignDialog.o: AssignDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) AssignDialog.cpp

$(OBJDIR)DaysDialog.o: DaysDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) DaysDialog.cpp

$(OBJDIR)ItineraryDialog.o: ItineraryDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ItineraryDialog.cpp

$(OBJDIR)ConfigDialog.o: ConfigDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ConfigDialog.cpp

$(OBJDIR)OptionsDialog.o: OptionsDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) OptionsDialog.cpp

$(OBJDIR)SignalDialog.o: SignalDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) SignalDialog.cpp

$(OBJDIR)TrackDialog.o: TrackDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TrackDialog.cpp

$(OBJDIR)TriggerDialog.o: TriggerDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TriggerDialog.cpp

$(OBJDIR)StationInfoDialog.o: StationInfoDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) StationInfoDialog.cpp

$(OBJDIR)TrainInfoDialog.o: TrainInfoDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TrainInfoDialog.cpp

$(OBJDIR)loadsave.o: loadsave.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) loadsave.cpp

$(OBJDIR)Main.o: Main.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) Main.cpp

$(OBJDIR)MainFrm.o: MainFrm.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) MainFrm.cpp

$(OBJDIR)run.o: run.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) run.cpp

$(OBJDIR)TConfig.o: TConfig.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TConfig.cpp

$(OBJDIR)TDFile.o: TDFile.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TDFile.cpp

$(OBJDIR)ReportBase.o: ReportBase.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ReportBase.cpp

$(OBJDIR)GraphView.o: GraphView.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) GraphView.cpp

$(OBJDIR)HtmlView.o: HtmlView.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) HtmlView.cpp

$(OBJDIR)ItineraryView.o: ItineraryView.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ItineraryView.cpp

$(OBJDIR)ToolsView.o: ToolsView.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ToolsView.cpp

$(OBJDIR)TimeTblView.o: TimeTblView.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TimeTblView.cpp

$(OBJDIR)NotebookMgr.o: NotebookMgr.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) NotebookMgr.cpp

$(OBJDIR)track.o: track.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) track.cpp

$(OBJDIR)trsim.o: trsim.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) trsim.cpp

$(OBJDIR)TSignal.o: TSignal.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) TSignal.cpp

$(OBJDIR)tdscript.o: tdscript.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) tdscript.cpp

$(OBJDIR)ScenarioInfoDialog.o: ScenarioInfoDialog.cpp
	$(CXXC) -c -o $@ $(GRID_CXXFLAGS) ScenarioInfoDialog.cpp

#td3_griddemo_rc.o: $(srcdir)/griddemo.rc
#	$(RESCOMP) -i$< -o$@   --define __WX$(TOOLKIT)__ $(__WXUNIV_DEFINE_p_2)  $(__EXCEPTIONS_DEFINE_p_2) $(__RTTI_DEFINE_p_2) $(__THREAD_DEFINE_p_2)   --include-dir $(srcdir) $(__DLLFLAG_p_2) --include-dir $(srcdir)/../../samples --include-dir $(top_srcdir)/include


# Include dependency info, if present:
-include .deps/*.d

.PHONY: all install uninstall clean distclean td3_bundle
