TD3_OBJECTS =  \
	$(__td3u_os2_lib_res) \
	$(OBJDIR)Canvas.o \
	$(OBJDIR)html.o \
	$(OBJDIR)http.o \
	$(OBJDIR)ItineraryView.o \
	$(OBJDIR)loadsave.o \
	$(OBJDIR)Main.o \
	$(OBJDIR)MainFrm.o \
	$(OBJDIR)run.o \
	$(OBJDIR)ReportBase.o \
	$(OBJDIR)TConfig.o \
	$(OBJDIR)TDFile.o \
	$(OBJDIR)GraphView.o \
	$(OBJDIR)LateGraphView.o \
	$(OBJDIR)HtmlView.o \
	$(OBJDIR)ToolsView.o \
	$(OBJDIR)TimeTable.o \
	$(OBJDIR)TimeTblView.o \
	$(OBJDIR)track.o \
	$(OBJDIR)Train.o \
	$(OBJDIR)trsim.o \
	$(OBJDIR)MotivePower.o \
	$(OBJDIR)NotebookMgr.o \
	$(OBJDIR)Alerts.o \
	$(OBJDIR)AlertList.o \
	$(OBJDIR)AssignDialog.o \
	$(OBJDIR)DaysDialog.o \
	$(OBJDIR)ItineraryDialog.o \
	$(OBJDIR)ConfigDialog.o \
	$(OBJDIR)OptionsDialog.o \
	$(OBJDIR)SignalDialog.o \
	$(OBJDIR)TrackDialog.o \
	$(OBJDIR)TriggerDialog.o \
	$(OBJDIR)TrainInfoDialog.o \
	$(OBJDIR)StationInfoDialog.o \
	$(OBJDIR)TrackScriptDialog.o \
	$(OBJDIR)TrainInfoList.o \
	$(OBJDIR)TSignal.o \
	$(OBJDIR)Itinerary.o \
	$(OBJDIR)Localize.o \
	$(OBJDIR)tdscript.o \
	$(OBJDIR)ScenarioInfoDialog.o \
	$(OBJDIR)FontManager.o \
	$(OBJDIR)PlatformGraph.o \
	$(OBJDIR)Puzzles.o \
	$(OBJDIR)Client.o \
	$(OBJDIR)ClientConnection.o \
	$(OBJDIR)AppMainLoop.o \
	$(OBJDIR)WebServices.o \
	$(OBJDIR)WSGenTT.o \
	$(OBJDIR)Server.o \
	$(OBJDIR)Shape.o \
	$(OBJDIR)TVector.o \
	$(OBJDIR)StringBuilder.o \
	$(OBJDIR)HostLock.o \
	$(OBJDIR)HostThread.o \
	$(OBJDIR)Options.o \
	$(OBJDIR)italiano.o \
	$(OBJDIR)SwitchBoard.o \
	$(OBJDIR)SwitchboardNameDialog.o \
	$(OBJDIR)SwitchboardView.o \
	$(OBJDIR)SkinColorsDialog.o \
	$(OBJDIR)GTFS.o \
	$(OBJDIR)CSV.o \
	$(OBJDIR)mongoose.o \
	$(__td3___win32rc)
